### ISSUE TITLE
Mending not working 1.20.1

### ISSUE THREAD

**Issue by Blonceh** [jaredlll08/Clumps#134]
So, i've downloaded a modpack ( Better MC 4, plus made a server to play with friends on that modpack) and after playing some of it, i had made an mob spawner and got some items with mending. I stayed some time afk so that zombies collect(i've disabled entity cramming so they can freely collect in one block) when i tried repairing my tools/armour mending wasn't working at all like it should've, after disabling it it works. 
**Is it possible to fix?**
**p.s. Would like to use this mod moving forward. good for fps**

(Mod Version: Clumps-forge-1.20.1-12.0.0.3)
Here are some images of the problem:
First 2 are with the mod disabled, as you can see it's working.
![image](https://github.com/jaredlll08/Clumps/assets/164582189/4f149a92-f0d5-42f5-90c0-2a2decf7c6fe)
![image](https://github.com/jaredlll08/Clumps/assets/164582189/1053c1dd-885c-4e01-a719-857ba7309c86)
The next 2 are with the mod enabled, as you can see i did get the xp but it went to the player instead of the tool.
![image](https://github.com/jaredlll08/Clumps/assets/164582189/414a5d52-5c4f-4a1e-8b0a-e0fc3ab215be)
![image](https://github.com/jaredlll08/Clumps/assets/164582189/3c516f7a-9fbf-4e18-9257-ad92c8831627)

**Comment by jaredlll08** [comment]
can I get a full modlist please

**Comment by Blonceh** [comment]
> can I get a full modlist please

https://www.modpackindex.com/modpack/64026/better-mc-forge-bmc4
Hope this helps.

**Comment by jaredlll08** [comment]
It does not, I would like the list of files that are actually on the server in the mods directory, I don't know what version of that modpack you are using, or if you may have forgotten that you added a mod.

The modpack you linked is very popular, and their last released version is from over a month ago, which is over 6 months since I last pushed an update of my mod for 1.20.1, if my mod wasn't working, it would have been reported by now.


Can you reproduce this in singleplayer, or only on the server?

**Comment by Blonceh** [comment]
It's the latest version of that modpack v26. I also don't know how to get you the list for all of the mods, if you could let me know how to i'd gladly do it.
Yes i can reproduce it in singleplayer.

**Comment by jaredlll08** [comment]
When you reproduce it in single player, is it on the same world or a different one?

I downloaded the pack, make a single player super flat world, put a broken netherite sword with mending in my offhand and am killing mobs, and mending appears to be working perfectly fine.

Are you sure you didn't add any mods to the modpack? Especially performance mods as they are prone to breaking clumps.

**Comment by Blonceh** [comment]
I didn't add any mods to the modpack. It's the same as the download file from curseforge. It's a different world, it doesn't work either way only way for it to work is disabling it.

**Comment by jaredlll08** [comment]
Can you try and reproduce the scenario I played out? Brand new super flat
world.

If you can't reproduce it, can you go into the super flat world, and hold
f3+c until the game crashes, then give me the crash log

**Comment by Blonceh** [comment]
So i did what you told me and apperently it just works fine after i restarted Minecraft and made a new superflat world. Yet the issue it's still going on, on my server.

**Comment by jaredlll08** [comment]
Who is your server host?

can you log into the server and run `/forge mods` and then give me your latest.log file

**Comment by Blonceh** [comment]
I'm the host.

**Comment by jaredlll08** [comment]
Okay, I can't see any apparent issue with your server log, and unfortunately I don't have all day to debug a modpack that I didn't make.

As it stands I believe that Clumps is working perfectly fine on it's own, in both single player and a server, so I can only assume that it is something about this modpack, you're going to need to report this to the modpack authors and let them figure it out, if it turns out it is actually something to do with clumps, then they should be able to provide me with more information on what is going on.

If the modpack authors aren't helpful, then the only suggestion I have would be to start removing mods from the server until it works, and then you should know what mod caused the issue.
