### ISSUE TITLE
Modrinth lists the Fabric API as a dependency, but it is not

### ISSUE THREAD

**Issue by YoshiRulz** [jaredlll08/Clumps#135]

**Comment by jaredlll08** [comment]
While not strictly required, it is heavily encouraged to have it installed due to events that Clumps fires for mod compat.

I would rather have it listed as a required dependency compared to dealing with issues saying that the mod compat doesn't work.

**Comment by YoshiRulz** [comment]
Thanks for the explanation. Searchables also has it listed as required despite being in `recommends`; am I right to assume that's for the same reason? And did you mean to have it as `recommends` in Clumps too, but forgot?

**Comment by jaredlll08** [comment]
Searchables actually has no reason to depend on Fabric API, I always add the fabric api when I start developing projects due to it being required for even the most basic thing such as loading resources, however in that mod's case I guess it isn't required at all.


As for the Fabric Mod Json, I don't have an answer for you there, it isn't something I usually spend too much time on when developing, so it is very likely that I just copied the file from another project and went to code the actual mod.

It should probably have fabric api in the recommends
