### ISSUE TITLE
Unable to use Mending

### ISSUE THREAD

**Issue by Gloval** [jaredlll08/Clumps#37]
XP Clumps bypassing offhand tool with mending and going into player Levels pool..
Unable to repair tool unless XP does not get a chance to clump up.

Mod Version 6.0.0.3 for 1.16.1

**Comment by Eydamos** [comment]
I can also confirm this bug. I have disabled the mod for now until this is fixed

**Comment by jaredlll08** [comment]
I can't reproduce, works fine in both main hand or off hand.

![Peek 2020-08-14 21-21](https://user-images.githubusercontent.com/5553605/90285462-44333280-de74-11ea-9d51-45efe2798f7d.gif)


What I will say though, the way that vanilla xp orbs do mending is that each orb can repair a single item, which works fine if you have multiple orbs (once they have finished repairing one item, they would move onto the next item), but that doesn't exactly work with clumps since it would just be one single orb, and that would only repair one item.

If you are having trouble with mending not working at *all*, then that is an issue with another mod messing with things.

I will think about how I want to handle mending though and possibly go through all items and try repair them, but that is unrelated to this issue.
